[tool.poetry]
name = "Pype"
version = "3.0.0"
description = "Multi-platform open-source pipeline built around the Avalon platform, expanding it with extra features and integrations."
authors = ["Pype Club <info@pype.club>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "3.7"
acre = { git = "https://github.com/pypeclub/acre.git" }
opentimelineio = { git = "https://github.com/pypeclub/OpenTimelineIO.git", branch="develop" }
appdirs = "^1.4.3"
arrow = "^0.15.5"
certifi = "*"
clique = "1.5.*"
Click = "^7"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
autopep8 = "^1.4"
cx_freeze = "^6.1"
jedi = "^0.13"
Jinja2 = "^2.11"
pycodestyle = "^2.5.0"
pydocstyle = "^3.0.0"
pylint = "^2.4.4"
pytest = "^5.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
